# Generated by Django 5.0.6 on 2024-07-03 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mychatapp', '0007_remove_profile_friend_friend_profile_friends_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='friends',
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frnd_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mychatapp.profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='friend',
            field=models.ManyToManyField(related_name='amigo', to='mychatapp.friends'),
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
