# Generated by Django 5.0.6 on 2024-07-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mychatapp', '0008_remove_profile_friends_friends_profile_friend_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='friend',
            field=models.ManyToManyField(blank=True, to='mychatapp.profile'),
        ),
    ]
