# Generated by Django 5.0.6 on 2024-07-05 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mychatapp', '0011_chatmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
