# Generated by Django 5.0.6 on 2024-07-07 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mychatapp', '0016_alter_chatmessage_receiver_alter_chatmessage_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='pub_date',
            field=models.DateTimeField(null=True),
        ),
    ]
