# Generated by Django 5.0.6 on 2024-07-08 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mychatapp', '0018_alter_chatmessage_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
